units:
#Change to choc by changing to cx and cy instead of u
  kx: u
  ky: u
  px: kx + 8
  py: ky + 8
points:
  key:
    padding: 1ky
    spread: 1kx
  zones:
    main:
       # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
      rows:
        bot:
        mid:
        top:
      columns:
        pinkie:
          rows:
            top.column_net: P21
            mid.column_net: P1
            bot.column_net: P0   
        ring:
          key:
            stagger: .4ky
          rows:
            top.column_net: P18
            mid.column_net: P19
            bot.column_net: P20   
        middle:
          key:
            stagger: .2ky
          rows:
            top.column_net: P16
            mid.column_net: P14
            bot.column_net: P15
        index:
          key:
            stagger: -.2ky    
          rows:
            top.column_net: P10
            mid.column_net: P6
            bot.column_net: P5
        index2:
          rows:
            top.column_net: P7
            mid.column_net: P8
            bot.column_net: P9
    thumb:
      anchor:
        ref: main_index2_bot
        shift: [1kx,-1.5ky]
        rotate: -30
      rows:     
      columns:
        one:
          key:
            width: 1.5kx
            splay: 75
            column_net: P3
        two:  
          key:
            width: 1.5kx   
            shift: [-1kx,-1ky]
            column_net: P2
        three: 
          key:
            shift: [-2.8kx,1.1ky]
            column_net: P4
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
      - ref: main_pinkie_bot
        shift: [-0.5px,-0.5py]
      - ref: main_pinkie_bot
        shift: [0.5px,-0.5py]        
      - ref: main_ring_bot
        shift: [0px,-0.5py]
      - ref: main_index_bot
        shift: [-0.5px,-0.5py]   
      - ref:  thumb_three
        shift: [-0.5px,0.5py]
      - ref:  thumb_three
        shift: [-0.5px,-0.5py]            
      - ref: thumb_one
        shift: [-.5px,-0.5py] 
      - ref: thumb_one
        shift: [-.5px,-0.5py] 
      - ref: thumb_two
        shift: [-.5px,-0.5py]   
      - ref: thumb_two
        shift: [.5px,-0.5py] 
      - ref: main_index2_bot
        shift: [0.8px,-.5py]
      - ref: main_index2_bot
        shift: [0.75px,-.25py]        
      - ref: main_index2_bot
        shift: [1.5px,-.250py]     
      - ref: main_index2_mid
        shift: [1.5px,-.5py]        
      - ref: main_index2_top
        shift: [1.5px,.75py]          
      - ref: main_middle_top
        shift: [-0.5px,0.5py] 
      - ref: main_ring_top
        shift: [-0.5px,0.5py]    
      - ref: main_pinkie_top
        shift: [-0.5px,0.5py]  
      - ref: main_pinkie_bot
        shift: [-0.5px,0.5py]           
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  petasi:
    outlines:
      main:
        outline: board
    footprints:
      mx_hotswap:
        what: mx
        where: true
        params:
          keycaps: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: main_index2_top
          shift: [1.45kx,-0.1ky]
          rotate: -90
      reset:
        what: wuerth-434121025816
        params:
          r1: RST
          r2: GND
        where:
          ref: main_index2_top
          shift: [1.25kx,-2ky]
          rotate: 0
      powerswitch:
          what: pcm12
          where:
            ref: main_index2_top
            shift: [2kx,-1.55ky]
            rotate: 90
          params:
            from: pos
            to: RAW
      battery:
          what: jst-s2b-ph-kl
          where:
            ref: main_index2_top
            shift: [1.25kx,-1.6ky]
            rotate: 180
          params:
            neg: GND
      switchviaraw:
          what: via
          where:
            ref: main_index2_top
            shift: [2kx,-2ky]
          params:
            net: RAW
      switchviapos:
          what: via
          where:
            ref: main_index2_top
            shift: [2kx,-2.1ky]
          params:
            net: pos